version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    env_file:
      - .env
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    networks:
      - app-network
  backend:
    build:
      context: ./backend
    ports:
      - "55002:55002"
    depends_on:
      - mongodb
      - mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge