version: '3'
services:
  frontend:
    build: 
      context: ./frontend
    ports:
      - "55001:55001"
    depends_on:
      - backend    # Changed back to simple dependency
    networks:
      - app-network

  backend:
    build: 
      context: ./backend
    ports:
      - "55002:55002"
    depends_on:
      - mongodb
      - mysql
    networks:
      - app-network
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=lab4DB
      - MONGO_URI=mongodb://mongodb:27017/schedules_db

  mongodb:
    build: 
      context: ./databases/nosql
    networks:
      - app-network
    environment:
      - MONGO_INITDB_DATABASE=schedules_db
      
  mysql:
    build: 
      context: ./databases/sql
    networks:
      - app-network
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=lab4DB

networks:
  app-network:
    driver: bridge